SELECT SUM(PRICE*COUNT)
FROM TRANSGOOD
WHERE ID IN
    ( SELECT OUTCOMEGOODS_ID
     FROM OUTCOMETRANS_TRANSGOOD
     WHERE OUTCOMETRANS_ID IN
         ( SELECT ID
          FROM OUTCOMETRANS
          WHERE USER_ID =:user_id
            AND DATE BETWEEN :start AND :stop))